spring.application.name=employee-api-with-jwt

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

# Pagination. No need to set default page number and page size as PageableDefault does it
spring.data.web.pageable.max-page-size=100
